# GitHub Actions Workflow for Deployment Readiness Check
name: Deployment Readiness Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  deployment-readiness:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Run deployment readiness check
      run: |
        python3 deployment_readiness_agent.py --json > deployment_report.json
        
    - name: Upload deployment report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: deployment-readiness-report
        path: deployment_report.json
        
    - name: Parse and display results
      if: always()
      run: |
        # Extract key metrics from JSON report
        DEPLOYMENT_READY=$(python3 -c "import json; data=json.load(open('deployment_report.json')); print(data['deployment_ready'])")
        ERROR_COUNT=$(python3 -c "import json; data=json.load(open('deployment_report.json')); print(data['error_count'])")
        WARNING_COUNT=$(python3 -c "import json; data=json.load(open('deployment_report.json')); print(data['warning_count'])")
        
        echo "## Deployment Readiness Report 🚀" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "$DEPLOYMENT_READY" = "True" ]; then
          echo "✅ **Repository is DEPLOYMENT READY!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Repository is NOT deployment ready**" >> $GITHUB_STEP_SUMMARY
          echo "- Critical issues: $ERROR_COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Warnings: $WARNING_COUNT" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📄 [Full report available in artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
        
    - name: Fail if not deployment ready
      run: |
        DEPLOYMENT_READY=$(python3 -c "import json; data=json.load(open('deployment_report.json')); print(data['deployment_ready'])")
        if [ "$DEPLOYMENT_READY" != "True" ]; then
          echo "❌ Deployment readiness check failed. Repository is not ready for production deployment."
          exit 1
        fi